/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class posix_MsgQ */

#ifndef _Included_posix_MsgQ
#define _Included_posix_MsgQ
#ifdef __cplusplus
extern "C" {
#endif
#undef posix_MsgQ_IPC_RMID
#define posix_MsgQ_IPC_RMID 0L
#undef posix_MsgQ_IPC_SET
#define posix_MsgQ_IPC_SET 1L
#undef posix_MsgQ_IPC_STAT
#define posix_MsgQ_IPC_STAT 2L
#undef posix_MsgQ_IPC_PRIVATE
#define posix_MsgQ_IPC_PRIVATE 0L
#undef posix_MsgQ_IPC_ALLOC
#define posix_MsgQ_IPC_ALLOC 32768L
#undef posix_MsgQ_IPC_CREAT
#define posix_MsgQ_IPC_CREAT 512L
#undef posix_MsgQ_IPC_EXCL
#define posix_MsgQ_IPC_EXCL 1024L
#undef posix_MsgQ_IPC_NOWAIT
#define posix_MsgQ_IPC_NOWAIT 2048L
#undef posix_MsgQ_IPC_CI
#define posix_MsgQ_IPC_CI 4096L
#undef posix_MsgQ_IPC_NOCLEAR
#define posix_MsgQ_IPC_NOCLEAR 8192L
#undef posix_MsgQ_IPC_PHYS
#define posix_MsgQ_IPC_PHYS 16384L
#undef posix_MsgQ_MSG_NOERROR
#define posix_MsgQ_MSG_NOERROR 4096L
/*
 * Class:     posix_MsgQ
 * Method:    msgget
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_posix_MsgQ_msgget
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     posix_MsgQ
 * Method:    msgctl
 * Signature: (IILposix/MsgQ/msqid_ds;)I
 */
JNIEXPORT jint JNICALL Java_posix_MsgQ_msgctl
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     posix_MsgQ
 * Method:    msgsnd
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_posix_MsgQ_msgsnd
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint);

/*
 * Class:     posix_MsgQ
 * Method:    msgsnd0
 * Signature: (IJII)I
 */
JNIEXPORT jint JNICALL Java_posix_MsgQ_msgsnd0
  (JNIEnv *, jclass, jint, jlong, jint, jint);

/*
 * Class:     posix_MsgQ
 * Method:    msgrcv
 * Signature: (I[I[BI)I
 */
JNIEXPORT jint JNICALL Java_posix_MsgQ_msgrcv
  (JNIEnv *, jclass, jint, jintArray, jbyteArray, jint);

/*
 * Class:     posix_MsgQ
 * Method:    msgrcv0
 * Signature: (IJIII)I
 */
JNIEXPORT jint JNICALL Java_posix_MsgQ_msgrcv0
  (JNIEnv *, jclass, jint, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
