/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class posix_Stat */

#ifndef _Included_posix_Stat
#define _Included_posix_Stat
#ifdef __cplusplus
extern "C" {
#endif
#undef posix_Stat_LNK
#define posix_Stat_LNK 0L
#undef posix_Stat_REG
#define posix_Stat_REG 1L
#undef posix_Stat_DIR
#define posix_Stat_DIR 2L
#undef posix_Stat_CHR
#define posix_Stat_CHR 3L
#undef posix_Stat_BLK
#define posix_Stat_BLK 4L
#undef posix_Stat_FIFO
#define posix_Stat_FIFO 5L
#undef posix_Stat_SOCK
#define posix_Stat_SOCK 6L
/*
 * Class:     posix_Stat
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_posix_Stat_init
  (JNIEnv *, jclass);

/*
 * Class:     posix_Stat
 * Method:    stat
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_posix_Stat_stat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     posix_Stat
 * Method:    lstat
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_posix_Stat_lstat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     posix_Stat
 * Method:    utime
 * Signature: (Ljava/lang/String;JJ)I
 */
JNIEXPORT jint JNICALL Java_posix_Stat_utime
  (JNIEnv *, jclass, jstring, jlong, jlong);

/*
 * Class:     posix_Stat
 * Method:    chown
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_posix_Stat_chown
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     posix_Stat
 * Method:    chmod
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_posix_Stat_chmod
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     posix_Stat
 * Method:    S_IS
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_posix_Stat_S_1IS
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     posix_Stat
 * Method:    umask
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_posix_Stat_umask__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     posix_Stat
 * Method:    umask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_posix_Stat_umask__
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
