/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class posix_SharedMem */

#ifndef _Included_posix_SharedMem
#define _Included_posix_SharedMem
#ifdef __cplusplus
extern "C" {
#endif
#undef posix_SharedMem_IPC_RMID
#define posix_SharedMem_IPC_RMID 0L
#undef posix_SharedMem_IPC_SET
#define posix_SharedMem_IPC_SET 1L
#undef posix_SharedMem_IPC_STAT
#define posix_SharedMem_IPC_STAT 2L
#undef posix_SharedMem_IPC_PRIVATE
#define posix_SharedMem_IPC_PRIVATE 0L
#undef posix_SharedMem_IPC_ALLOC
#define posix_SharedMem_IPC_ALLOC 32768L
#undef posix_SharedMem_IPC_CREAT
#define posix_SharedMem_IPC_CREAT 512L
#undef posix_SharedMem_IPC_EXCL
#define posix_SharedMem_IPC_EXCL 1024L
#undef posix_SharedMem_IPC_NOWAIT
#define posix_SharedMem_IPC_NOWAIT 2048L
#undef posix_SharedMem_IPC_CI
#define posix_SharedMem_IPC_CI 4096L
#undef posix_SharedMem_IPC_NOCLEAR
#define posix_SharedMem_IPC_NOCLEAR 8192L
#undef posix_SharedMem_IPC_PHYS
#define posix_SharedMem_IPC_PHYS 16384L
#undef posix_SharedMem_SHM_SIZE
#define posix_SharedMem_SHM_SIZE 6L
#undef posix_SharedMem_SHM_RDONLY
#define posix_SharedMem_SHM_RDONLY 4096L
#undef posix_SharedMem_SHM_RND
#define posix_SharedMem_SHM_RND 8192L
/*
 * Class:     posix_SharedMem
 * Method:    getLBA
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_posix_SharedMem_getLBA
  (JNIEnv *, jclass);

/*
 * Class:     posix_SharedMem
 * Method:    shmctl
 * Signature: (IILposix/SharedMem/shmid_ds;)I
 */
JNIEXPORT jint JNICALL Java_posix_SharedMem_shmctl
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     posix_SharedMem
 * Method:    shmat
 * Signature: (IJI)J
 */
JNIEXPORT jlong JNICALL Java_posix_SharedMem_shmat
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     posix_SharedMem
 * Method:    shmdt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_posix_SharedMem_shmdt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     posix_SharedMem
 * Method:    shmget
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_posix_SharedMem_shmget
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
